feed/urls.py
from django.urls import path
from .views import HomePageView, PatternDetailView

app_name = 'feed'

urlpatterns = [path('', HomePageView.as_view(), name='feed'),
               path('pattern/<int:pk>/', PatternDetailView.as_view(), name='detail')]

gknit/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path, include, re_path

# App URLS
from feed import urls as feed_urls
from pattern import urls as pattern_urls
from profiles import urls as profile_urls

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('', include(feed_urls), name='feed'),
    path('', include(pattern_urls), name='patterns'),
    path('profile/', include(profile_urls), name='profile'),
    path("accounts/", include("allauth.urls"), name='accounts'),
    path('search/', include('search.urls'), name='search'),
    re_path('', include("allauth.urls"))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pattern/urls.py
from . import views
from django.urls import path
from .views import UploadPatternView

app_name = "pattern"

urlpatterns = [
    path('', views.PatternView.as_view(), name="pattern"),
    path('add/', UploadPatternView.as_view(), name="add"),
    path('edit/<int:pattern_id>/', views.edit_pattern, name="edit"),
    path('pattern/<int:pk>/remove/', views.delete_pattern, name="delete"),
]

profiles/urls.py
from django.urls import path
from . import views
from .views import ProfileView

app_name = 'profiles'

urlpatterns = [
    path("<str:username>/", views.ProfileView.as_view(), name='profile'),
    path("<str:username>/edit/", views.edit_profile, name='edit'),
    path('<str:username>/remove/', views.delete_profile, name="delete"),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path("", views.SearchView.as_view(), name='search'),
]

templates/includes/navbar.html
{% load thumbnail %}
{% load static %}
{% load cloudinary %}


<!-- Style navbar to same colour as BG so screen readers can see it but leaves a seamless look for sighted users-->
<nav class="navbar" style="background-color: #ced4da;">
    <div class="container d-lg-none">
        <div>

          <!-- Offcanvas -->
            <button class="btn" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNav">
                <img
                    src="https://res.cloudinary.com/duekocfq6/image/upload/f_auto,q_auto/v1/static/icon-menu"
                    alt="3 bar menu" height="50px" width="50px">
            </button>
            <div class="offcanvas offcanvas-start" tabindex="-1"
                id="offcanvasNav">

                <div class="offcanvas-header">
                    {% if request.user.is_authenticated %}
                    <h5 class="offcanvas-title">
                        Welcome, {{user.username}}!</h5>
                    {% else %}
                    <h5 class="offcanvas-title">
                        Welcome!</h5>
                    {% endif %}
                    <button type="button" class="btn-close"
                        data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div>
                        Where to?
                    </div>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active"
                                href="{% url 'feed:feed' %}">
                                <img
                                    src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012318/static/icon-home.png"
                                    alt="home" width="50px" height="50px">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'search:search' %}">
                                <img
                                    src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012362/static/icon-search.png"
                                    alt="search" width="50px" height="50px">
                                Search
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'pattern:add' %}">
                                <img
                                    src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012296/static/icon-add.png"
                                    alt="add pattern" width="50px"
                                    height="50px">
                                Add pattern
                            </a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'profiles:profile' user.username %}">
                                <img
                                    src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012340/static/icon-profile.png"
                                    alt="My profile" width="50px" height="50px">
                                My Profile</a>
                        </li>
                        {% else %}
                        {% endif %}
                        <li class="nav-item">
                            {% if request.user.is_authenticated %}
                            <a class="nav-link"
                                href="{% url 'account_logout' %}">
                                <img
                                    src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012278/static/icon-signout.png"
                                    alt="Sign out" width="50px" height="50px">
                                Sign Out</a>
                            {% else %}
                            <a class="nav-link"
                                href="{% url 'account_login' %}">
                                <img
                                    src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012390/static/icon-signin.png"
                                    alt="Log in" width="50px" height="50px">
                                Login
                            </a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Navbar Branding -->
        <a class="navbar-brand" href="{% url 'feed:feed' %}">
            <!-- Large screen brand  -->
            <img class="img-fluid d-none d-sm-block"
            src="https://res.cloudinary.com/duekocfq6/image/upload/v1708004906/static/logo-lg_idyzwe.png"
            alt="Generation Knit" width="300" height="60">
                
            <!-- Small screen brand  -->
            <img class="img-fluid d-sm-none"
                src="https://res.cloudinary.com/duekocfq6/image/upload/v1708008204/static/logo-sm_zomalv.png"
                alt="Generation Knit" width="90" height="50">
        </a>
        <!-- Show user information in top right -->
        {% if request.user.is_authenticated %}
        <div class="float-end justify-content-end rounded d-none d-md-block" id="user-information" style="background-color: #A8A8A8; padding-left: 10px;">
            <a class="nav-link"
                href="{% url 'profiles:profile' user.username %}">
                {{ request.user.username}}
                <img src="{% cloudinary_url user.profile.image.url format="auto" quality="auto" width=50 height=50 crop="fill" gravity="center" %}" alt="user icon" class="img-thumbnail thumbnail-50px"> 
            </a>
            {% else %}
            <a class="nav-link"
                href="{% url 'account_login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>
    <!-- Large screen nav-->
    
<nav class="navbar navbar-expand-lg navbar-light bg-dark-subtle d-none d-lg-block">
    <div class="container">
        <div class="row row-cols-3">
            <div class="col">
            </div>
            <div class="col">
                <a class="navbar-brand" href="{% url 'feed:feed' %}">
                    <img class="img-fluid"
                        src="https://res.cloudinary.com/duekocfq6/image/upload/v1708004906/static/logo-lg_idyzwe.png"
                        alt="Generation Knit">
                </a>
            </div>
            <div class="col">
                <!-- Show user information in top right -->
            {% if request.user.is_authenticated %}
            <div class="float-end justify-content-end rounded" id="user-information" style="background-color: #A8A8A8; padding-left: 10px;">
                    <a class="nav-link"
                        href="{% url 'profiles:profile' user.username %}">
                        {{ request.user.username}}
                        <img src="{% cloudinary_url user.profile.image.url format="auto" quality="auto" width=50 height=50 crop="fill" gravity="center" %}" alt="user icon" class="img-thumbnail thumbnail-50px"> 
                    </a>
                {% else %}
                    <a class="nav-link float-end"
                        href="{% url 'account_login' %}">Login
                    </a>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="container">
            <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
              <div class="col-3 mb-2 mb-md-0">
              </div>
              <ul class="nav col-12 col-auto mb-2 justify-content-center mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active"
                        href="{% url 'feed:feed' %}">
                        <img
                            src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012318/static/icon-home.png"
                            alt="home" width="50px" height="50px">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        href="{% url 'search:search' %}">
                        <img
                            src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012362/static/icon-search.png"
                            alt="search" width="50px" height="50px">
                        Search
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        href="{% url 'pattern:add' %}">
                        <img
                            src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012296/static/icon-add.png"
                            alt="add pattern" width="50px"
                            height="50px">
                        Add pattern
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link"
                        href="{% url 'profiles:profile' user.username %}">
                        <img
                            src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012340/static/icon-profile.png"
                            alt="My profile" width="50px" height="50px">
                        My Profile</a>
                </li>
                {% else %}
                {% endif %}
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                    <a class="nav-link"
                        href="{% url 'account_logout' %}">
                        <img
                            src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012278/static/icon-signout.png"
                            alt="Sign out" width="50px" height="50px">
                        Sign Out</a>
                    {% else %}
                    <a class="nav-link"
                        href="{% url 'account_login' %}">
                        <img
                            src="https://res.cloudinary.com/duekocfq6/image/upload/v1708012390/static/icon-signin.png"
                            alt="Log in" width="50px" height="50px">
                        Login
                    </a>
                    {% endif %}
                </li>
            </ul>
        
              <div class="col-md-3 text-end">
  
              </div>
            </header>
          </div>
    </div>
</nav>