feed/urls.py
from django.urls import path
from .views import HomePageView, PatternDetailView

app_name = 'feed'

urlpatterns = [path('', HomePageView.as_view(), name='feed'),
               path('pattern/<int:pk>/', PatternDetailView.as_view(), name='detail')]

gknit/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path, include, re_path

# App URLS
from feed import urls as feed_urls
from pattern import urls as pattern_urls
from profiles import urls as profile_urls

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('', include(feed_urls), name='feed'),
    path('', include(pattern_urls), name='patterns'),
    path('profile/', include(profile_urls), name='profile'),
    path("accounts/", include("allauth.urls"), name='accounts'),
    path('search/', include('search.urls'), name='search'),
    re_path('', include("allauth.urls"))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pattern/urls.py
from . import views
from django.urls import path
from .views import UploadPatternView

app_name = "pattern"

urlpatterns = [
    path('', views.PatternView.as_view(), name="pattern"),
    path('add/', UploadPatternView.as_view(), name="add"),
    path('edit/<int:pattern_id>/', views.edit_pattern, name="edit"),
    path('pattern/<int:pk>/remove/', views.delete_pattern, name="delete"),
]

profiles/urls.py
from django.urls import path
from . import views
from .views import ProfileView

app_name = 'profiles'

urlpatterns = [
    path("<str:username>/", views.ProfileView.as_view(), name='profile'),
    path("<str:username>/edit/", views.edit_profile, name='edit'),
    path('<str:username>/remove/', views.delete_profile, name="delete"),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path("", views.SearchView.as_view(), name='search'),
]

pattern/models.py
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from cloudinary.models import CloudinaryField
from upload_validator import FileTypeValidator

# Pattern view ERD 
#  ____________________
# |Name of Pattern_____|    X  
# |Image_______________|    x
# |Pattern PDF_________|    X
# |Pattern notes_______|    X 
# |Published by User___| F  X
# |Date published _____|    X
# |Category of Pattern_|    x
# |Yarn Weight_________|    x
# |Needle size_________|    X


class Pattern(models.Model):
    CATEGORY = (
        (0, ''), 
        (1, 'Sweater'), 
        (2, 'Cardigan'), 
        (3, 'Skirt'), 
        (4, 'Pants'), 
        (5, 'Hat'), 
        (6, 'Scarf')
        )
    WEIGHT = (
        (0, 'Cobweb'), 
        (1, 'Lace'), 
        (2, 'Fingering'), 
        (3, 'DK'), 
        (4, 'Worsted')
        )
    NEEDLE = (
        (0, '1mm'), 
        (1, '2mm'), 
        (2, '3mm'), 
        (3, '4mm')
        )
    #Pattern title
    title = models.CharField(max_length=200, unique=True)
    #Pattern posted by
    author = models.ForeignKey(
    User, 
    on_delete=models.CASCADE, 
    )
    #Pattern notes
    content = models.TextField()
    #Post created on
    created_on = models.DateTimeField(auto_now=True)
    #Pattern category
    category = models.IntegerField(choices=CATEGORY, default=0)
    #Yarn Weight
    weight = models.IntegerField(choices=WEIGHT, default=0)
    #Needle size
    needle = models.IntegerField(choices=NEEDLE, default=0)
    # Image
    image = ImageField(upload_to='media/')
    # PDF
    pdf = models.FileField(upload_to='pdfs/', blank=True)
    # Link to Pattern
    link_pattern = models.CharField(blank=True)
        

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = ImageField(default='media/profiles/user-temp_mdiwia.png', upload_to="profiles/")
    bio = models.TextField(max_length=500)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    # Creates a profile on creation of User, to be customsed
    if created:
        Profile.objects.create(user=instance)
    

search/models.py
from django.db import models

# Create your models here.

profiles/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from django.shortcuts import render, get_object_or_404, redirect
from django.core.validators import FileExtensionValidator
from .models import Profile

# Allow user to edit their profile
class EditProfile(forms.ModelForm):
    image = forms.ImageField(
        required=False,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]
    )
    bio = forms.CharField(widget=SummernoteWidget)

    class Meta:
        model = Profile
        fields = [ 'image', 'bio']

profiles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.views.generic import DetailView, ListView
from django.contrib import messages
from .models import Profile
from pattern.models import Pattern
from .forms import EditProfile

# Create your views here.

class ProfileView(DetailView):
    http_method_names = ['get']
    template_name = 'profile.html'
    model = User
    context_object_name = 'user'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patterns'] = Pattern.objects.filter(author=self.object)
        context['num_patterns'] = self.get_num_patterns()
        return context

    def get_num_patterns(self):
        return Pattern.objects.filter(author=self.object).count()
        
    
def edit_profile(request, username):
    profile = get_object_or_404(Profile, user=request.user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Profile was edited successfully.")
            return redirect('profiles:profile', username=request.user)
    else:
        form = EditProfile(instance=profile)
    return render(request, 'edit_profile.html', {'form': form})




def delete_profile(request, username):
    profile = get_object_or_404(Profile, user__username=username)
    user = get_object_or_404(User, username=username)
    profile.delete()
    user.delete()
    messages.add_message(request, messages.SUCCESS, "Your profile was deleted.")
    return redirect('feed:feed')

search/views.py
from django.shortcuts import render
from pattern.models import Pattern
from django.views.generic import ListView
from django.db.models import Q

class SearchView(ListView):
    model = Pattern
    template_name = 'search.html'

    def get_queryset(self):
        query = self.request.GET.get('p')
        needle = self.request.GET.get('needle')
        category = self.request.GET.get('category')
        weight = self.request.GET.get('weight')
        paginate_by = 8

        # Is not None means that page will still render when no query is entered 
        if query is not None:
            patterns = Pattern.objects.filter(
                # Searches title, author and content body for a match
                Q(title__icontains=query) | Q(author__username__icontains=query) | Q(content__icontains=query)
            )
        else:
            patterns = Pattern.objects.none()

        # Pattern filters
        if needle is not None and needle.isdigit():
            patterns = patterns.filter(needle=int(needle))

        if category is not None and category.isdigit():
            patterns = patterns.filter(category=int(category))

        if weight is not None and weight.isdigit():
            patterns = patterns.filter(weight=int(weight))

        return patterns
    

templates/edit_pattern.html
{% extends "base.html" %}

{% block title %}Upload your pattern{% endblock %}
{% block script %}
        <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>
{% endblock%}



{% block body %}
    <div class="card m-3">
        <div class="card-body">
            <form method="POST" action="." enctype="multipart/form-data">
                {% csrf_token %} 
                {% for field in form %}
                <div class="mb-3 form-control">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label> {{ field }}
                </div>
                {% endfor %}
                <div>
                    <button type="submit" class="btn btn-dark">Submit</button>
                </div>
            </form>
        </div>
    </div>
    {% endblock %}

templates/edit_profile.html
{% extends "base.html" %} 
{% block title %}
Edit your profile 
{% endblock %} 

{% block body %}
    <div class="card m-3">
        <div class="card-body">
            <form method="POST" action="." enctype="multipart/form-data">
                {% csrf_token %} 
                {% for field in form %}
                <div class="mb-3 form-control">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label> {{ field }}
                </div>
                {% endfor %}
                <div>
                    <button type="submit" class="btn btn-dark">Submit</button>
                </div>
            </form>
        </div>
    </div>
    {% endblock %}

templates/home.html
{% extends "base.html" %}
{% load cloudinary %}

{% block title %}
Generation Knit
{% endblock %}

{% block body %}
<div class="container d-flex col col-md-auto flex-column align-items-center rounded" style="background-color: #A8A8A8;">
    {% for pattern in patterns %}

    <div class="card d-flex flex-column" style="max-width: 30rem;">
        <div class="text-center">
            <h3>
                {{ pattern.title }}
            </h3>
        </div>
        <a href="{% url 'feed:detail' pattern.id %}">
            <img src="{% cloudinary_url pattern.image.url format="auto" quality="auto" width=400 height=400 crop="fill" gravity="auto" %}" class="img-fluid" alt="pattern preview" style="object-fit: cover; height: 400px; width: 400px;">
        </a> 
        <div class="card-body flex-grow-1">
            <p class="card-text float-end">
                by
                <a href="{% url 'profiles:profile' pattern.author.username %}"
                    class="text-decoration-none link-secondary">
                    <b>{{ pattern.author }}</b>
                    <img src="{% cloudinary_url pattern.author.profile.image.url format="auto" quality="auto" width=50 height=50 crop="fill" gravity="center" %}" alt="user icon" class="img-thumbnail thumbnail-50px">                
                </a>
            </p>
        </div>
    </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-dark">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-dark">Previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-dark">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-dark">Last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock %}

templates/pattern_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cloudinary %}
{% block title %}{{ pattern.title}} by {{pattern.author.username}}{% endblock %}

{% block body %}
<div class="container-fluid d-flex justify-content-center">
    <div class="card" style="width: 18rem; border: 5px solid white;">
        <img src="{% cloudinary_url object.image.url format="auto" quality="auto" width=50 height=50 crop="fill" gravity="center" %}" 
        alt="pattern image"
        style="width: 100%; height: auto;"> 
    </div>
</div>

<div class="container-fluid d-flex justify-content-center">
    <div>
        <h1>
            {{ object.title }}
        </h1>
    </div>
</div>

<!-- Buttons for logged in member only -->
{% if request.user.is_authenticated and pattern.author == request.user %}
<div class="container-fluid d-flex justify-content-center">
    <div class="btn-group" role="group" aria-label="Edit or delete pattern">
        <a href="{% url 'pattern:edit' pattern.id %}" class="btn btn-dark">
            Edit
        </a>
        <a href="{% url 'pattern:delete' pattern.id %}" class="btn btn-dark">
            Delete
        </a>
    </div>
</div>
{% endif %}

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button"
                data-bs-toggle="collapse" data-bs-target="#collapseOne"
                aria-expanded="true" aria-controls="collapseOne">
                Description
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show"
            aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                {{ pattern.content|safe }}
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button"
                data-bs-toggle="collapse" data-bs-target="#collapseTwo"
                aria-expanded="false" aria-controls="collapseTwo">
                Pattern Information
            </button>
        </h2>
        <!-- Get pattern information for table -->
        <div id="collapseTwo" class="accordion-collapse collapse"
            aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th scope="row">Category</th>
                            <td>{{ pattern.get_category_display }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Yarn Weight</th>
                            <td>{{ pattern.get_weight_display }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Needle Size</th>
                            <td>{{ pattern.get_needle_display }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#collapseThree"
                    aria-expanded="false" aria-controls="collapseThree">
                    About the Author
                </button>
            </h2>
            <div id="collapseThree" class="accordion-collapse collapse"
                aria-labelledby="headingThree"
                data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <a
                        href="{% url 'profiles:profile' pattern.author.username %}">
                        <div class="container">
                            <img src="{% cloudinary_url user.profile.image.url format="auto" quality="auto" width=50 height=50 crop="fill" gravity="center" %}" 
                            alt="user icon" 
                            class="img-thumbnail thumbnail-50px float-end"> 
                            <h4 class="align-middle p-2">
                                {{ pattern.author.username }}
                            </h4>
                        </a>
                    </div>
                    <br>
                    <hr>
                    <p>
                      <!-- Get bio of user without HTML injection -->
                        {{ pattern.author.profile.bio|safe }}
                    </p>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="get-pattern">
                <button class="accordion-button collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#collapseFour"
                    aria-expanded="false" aria-controls="collapseFour">
                    Get the Pattern
                </button>
            </h2>
            <!-- Buttons only appear when PDF or Link is attached to a pattern -->
            <div id="collapseFour" class="accordion-collapse collapse"
                aria-labelledby="get-pattern"
                data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <div class="container">
                        {% if pattern.link_pattern %}
                        <a href="{{pattern.link_pattern}}" target="_blank"
                            class="btn btn-dark">
                            Link to external pattern
                        </a>
                        {% endif %}
                        {% if pattern.pdf %}
                        <a href="{{pattern.pdf.url}}" target="_blank"
                            class="btn btn-dark">
                            Link to PDF
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load cloudinary %}

{% block title %}
{{ user }}'s Profile
{% endblock %} 

{% block body %}
<div class="container">
    <div class="row rounded" style="background-color: #A9A9A9;">
        <!-- Profile picture -->
        <div class="col-lg-6 d-flex justify-content-center p-3">
            <p class="card-text">
                <img src="{% cloudinary_url user.profile.image.url format='auto' quality='auto' width=200 height=200 crop='fill' %}" alt="user profile picture" class="img-thumbnail">
            </p>
        </div>

        <!-- Bio and pattern number -->
        <div
            class="col-lg-6 d-flex flex-column align-items-lg-start align-items-center">
            <div class="card mb-3 mt-3">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ user.username }}
                    </h5>
                    {{ user.profile.bio|safe }}
                </div>
                <table class="table table-hover">
                    <thead>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">Patterns:</th>
                            <td>{{ num_patterns }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <h2 style="margin-top: 50px;">Patterns by {{user.username }}:</h2>
    <!-- Styling for small screen -->
    <div class="row d-lg-none">
        {% for pattern in patterns %}
        <div class="card col-12 ">
            <div class="row">
                <div class="col">
                    <a href="{% url 'feed:detail' pattern.id %}"
                        class="nav-link">
                        <img src="{% cloudinary_url pattern.image.url format='auto' quality='auto' width=100 height=100 crop='fill' %}" class="img-fluid" alt="pattern thumbnail" style="object-fit: cover; height: 100px; width: 100px">
                        {{ pattern.title}}
                    </a>
                </div>
                <div class="col d-flex justify-content-end align-items-center">
                    <a
                        href="{% url 'profiles:profile' pattern.author.username %}"
                        class="text-decoration-none link-secondary ">
                        {{ pattern.author }}
                        <img src="{% cloudinary_url pattern.author.profile.image.url format="auto" quality="auto" width=50 height=50 crop="fill" %}" class="thumbnail-50px" alt="user icon">
                    </a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="card">
            <div class="card-body">
                <p>This author has not authored any patterns</p>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Styling for large screen -->
    <div class="row d-none d-lg-flex rounded border p-4"  style="border: 4px solid #A9A9A9 !important;">
        {% for pattern in patterns %}
        <div class="col-lg-3 p-0">
            <div class="card d-flex flex-column">
                <div class="text-center">
                    <h6>
                        {{ pattern.title }}
                    </h6>
                </div>
                <div class="d-flex justify-content-center align-items-center" style="flex-grow: 1;">
                    <a href="{% url 'feed:detail' pattern.id %}">
                        <img src="{% cloudinary_url pattern.image.url format="auto" quality="auto" width=300 height=300 crop="fill" %}" class="img-fluid" alt="pattern thumbnail" style="object-fit: cover; height: 300px; width: 300px">
                    </a>
                </div>
                <div class="card-body mt-auto">
                    <p class="card-text float-end ">
                        by
                        <a
                            href="{% url 'profiles:profile' pattern.author.username %}"
                            class="text-decoration-none link-secondary">
                            <b>{{ pattern.author }}</b>
                            <img src="{% cloudinary_url pattern.author.profile.image.url format="auto" quality="auto" width=50 height=50 crop="fill" %}" class="img-fluid thumbnail-50px" alt="user icon"> 
                        </a>
                    </p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="card">
            <div class="card-body">
                <p>This author has not authored any patterns</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- Buttons for logged in member only -->
{% if request.user.is_authenticated and user.username == request.user.username %}
<div class="container-fluid d-flex justify-content-center m-5">
    <div class="btn-group" role="group" aria-label="Edit or delete profile">
        <a href="{% url 'profiles:edit' user.username %}" class="btn btn-dark" aria="edit profile">
            Edit profile
        </a>
        <a href="{% url 'profiles:delete' user.username %}" class="btn btn-danger" aria="delete profile">
            Delete profile
        </a>
    </div>
</div>
{% endif %}
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cloudinary %}

{% block title%}
Search
{% endblock %}
{% block body %}
<!-- Small screen styling -->
<div class="d-sm-none" style="background-color: #A8A8A8; border: 5px solid #A8A8A8;">
    <form action="{% url 'search:search' %}" method="GET">
        <div class="mb-3">
            <input name="p" type="text" class="form-control mb-3"
                placeholder='Search' aria-label="Search bar"
                aria-describedby="search-bar">
        </div>
        <div class="mb-3">
            <select class="form-select" name="weight"
                aria-label="Search by yarn weight">
                <option selected value="none">Yarn Weight</option>
                <option value="0">Cobweb</option>
                <option value="1">Lace</option>
                <option value="2">Fingering</option>
                <option value="3">DK</option>
                <option value="4">Worsted</option>
            </select>
            <select class="form-select" name="category"
                aria-label="Search by project type">
                <option selected value="none">Category</option>
                <option value="1">Sweater</option>
                <option value="2">Cardigan</option>
                <option value="3">Skirt</option>
                <option value="4">Pants</option>
                <option value="5">Hat</option>
                <option value="6">Scarf</option>
            </select>
            <select class="form-select" name="needle_size"
                aria-label="Search by needle size">
                <option selected value="none">Needle size</option>
                <option value="0">1mm</option>
                <option value="1">2mm</option>
                <option value="2">3mm</option>
                <option value="3">4mm</option>
            </select>
        </div>
        <button class='btn btn-dark d-md-none' type='submit' id='search'
            aria-label="Go">Search for Patterns</button>
    </form>
</div>

<!-- Large screen styling -->
<div class="d-none d-sm-block row rounded" style="background-color: #A8A8A8; border: 5px solid #A8A8A8;">
    <form action="{% url 'search:search' %}" method="GET" class="row mt-3">
        <div class="col p-0">
            <input name="p" type="text" class="form-control mb-3"
                placeholder='Search' aria-label="Search bar"
                aria-describedby="search-bar">
        </div>
        <div class="col input-group mb-3">
            <select class="form-select" name="weight"
                aria-label="Search by yarn weight">
                <option selected value="none">Yarn Weight</option>
                <option value="0">Cobweb</option>
                <option value="1">Lace</option>
                <option value="2">Fingering</option>
                <option value="3">DK</option>
                <option value="4">Worsted</option>
            </select>
            <select class="form-select" name="category"
                aria-label="Search by project type">
                <option selected value="none">Category</option>
                <option value="1">Sweater</option>
                <option value="2">Cardigan</option>
                <option value="3">Skirt</option>
                <option value="4">Pants</option>
                <option value="5">Hat</option>
                <option value="6">Scarf</option>
            </select>
            <select class="form-select" name="needle_size"
                aria-label="Search by needle size">
                <option selected value="none">Needle size</option>
                <option value="0">1mm</option>
                <option value="1">2mm</option>
                <option value="2">3mm</option>
                <option value="3">4mm</option>
            </select>
        </div>
    </div>
    <div style="background-color: #A8A8A8; border: 5px solid #A8A8A8;">
        <div class="col-md-1 offset-md-1 mb-3" style="width: 30%;">
            <button class='btn btn-dark d-none d-sm-block' type='submit' id='search'
                aria-label="Go">Search for Patterns</button>
        </div>
    </form>
</div>

{% if request.GET %}
<h6 class="m-3">
    Search results:
</h6>

<div class="container rounded p-3" style="border: 4px solid #A8A8A8;">
    <!-- Large Screen Layout -->
    <div class="row d-none d-lg-flex">
        {% for p in object_list %}
        <div class="col-lg-3 p-0">
            <div class="card d-flex flex-column">
                <div class="text-center">
                    <h3 class="nav-link">
                        {{ p.title }}
                    </h3>
                </div>
                <div class="d-flex justify-content-center align-items-center" style="flex-grow: 1;">
                    <a href="{% url 'feed:detail' p.id %}">
                        <img src="{% cloudinary_url p.image.url format="auto" quality="auto" width=300 height=300 crop="fill" gravity="auto" %}" 
                        class="img-fluid" 
                        style="object-fit: cover; height: 300px; width: 300px"
                        alt="{{ p.title }}">
                    </a>
                </div>
                <div class="card-body">
                    <p class="card-text float-end">
                        by
                        <a href="{% url 'profiles:profile' p.author.username %}"
                            class="text-decoration-none link-secondary nav-link">
                            <b>{{ p.author }}</b>
                            <img src="{% cloudinary_url p.author.profile.image.url format="auto" quality="auto" width=50 height=50 crop="fill" gravity="center" %}" 
                                 alt="user icon" 
                                 class="img-thumbnail thumbnail-50px">
                        </a>
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Small Screen Layout -->
    <div class="row d-lg-none">
        {% for p in object_list %}
        <div class="card col-12 ">
            <div class="row">
                <div class="col">
                    <a href="{% url 'feed:detail' p.id %}" class="nav-link">
                        <img src="{% cloudinary_url p.image.url format="auto" quality="auto" width=100 height=100 crop="fill" gravity="auto" %}" 
                        class="img-fluid" 
                        style="object-fit: cover; width: 100px; height: 100px;"
                        alt="{{ p.title }}">
                        {{ p.title}}
                    </a>
                </div>
                <div class="col d-flex justify-content-end align-items-center">
                    <a href="{% url 'profiles:profile' p.author.username %}"
                        class="text-decoration-none link-secondary nav-link">
                        {{ p.author }}
                        <img src="{% cloudinary_url p.author.profile.image.url format="auto" quality="auto" width=50 height=50 crop="fill" gravity="center" %}" 
                        alt="user icon" 
                        class="img-thumbnail thumbnail-50px">
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if p in object_list %}
    <div class="pagination card">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-dark">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-dark">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</div>

</div>
{% endif %}
{% endblock %}